@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour redémarrerJeu
participant ":JeuDeDes" as c
participant "joueurs: Map<String, Joueur>" as jm
-> c: redemarrerJeu()
note right
Selon Contrôleur 
(JeuDeDés est 
l'objet racine)
end note
c -> jm: clear()
note right
selon Expert
end note
@enduml
